controller_list:
  - name: fake_sixaxis_controller
    type: $(arg fake_execution_type)
    joints:
      - saj1
      - saj2
      - saj3
      - saj4
      - saj5
      - saj6
  - name: fake_scara_controller
    type: $(arg fake_execution_type)
    joints:
      - sj1
      - sj2
      - sj3
      - sjEE
initial:  # Define initial robot poses per group
  - group: sixaxis
    pose: home_sixaxis
  - group: scara
    pose: home_scara