controller_list:
  - name: fake_scara_group_controller
    type: $(arg fake_execution_type)
    joints:
      - sj1
      - sj2
      - sj3
      - sEE
  - name: fake_sixaxis_group_controller
    type: $(arg fake_execution_type)
    joints:
      - saj1
      - saj2
      - saj3
      - saj4
      - saj5
      - saj6
  - name: fake_pillar_group_controller
    type: $(arg fake_execution_type)
    joints:
      - pj1
      - pj2
      - pj3
      - pj4
initial:  # Define initial robot poses per group
  - group: scara_group
    pose: scara_home
  - group: sixaxis_group
    pose: sixaxis_home
  - group: pillar_group
    pose: pillar_home