scara:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.5  #davor 0.005
  kinematics_solver_timeout: 1  #davor 0.5
  goal_joint_tolerance: 1 #davor 0.01
  goal_position_tolerance: 1 #davor 0.5
  goal_orientation_tolerance: 1 #davor 0.05
sixaxis:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.5  #davor 0.005
  kinematics_solver_timeout: 1  #davor 0.5
  goal_joint_tolerance: 1 #davor 0.01
  goal_position_tolerance: 1 #davor 0.5
  goal_orientation_tolerance: 1 #davor 0.05
pillar:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.5  #davor 0.005
  kinematics_solver_timeout: 1  #davor 0.5
  goal_joint_tolerance: 1 #davor 0.01
  goal_position_tolerance: 1 #davor 0.5
  goal_orientation_tolerance: 1 #davor 0.05