sixaxis:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  #kinematics_solver_attempts: 3
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.01
  goal_position_tolerance: 0.5
  goal_orientation_tolerance: 0.05
scara:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  #kinematics_solver_attempts: 3
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.01
  goal_position_tolerance: 0.5
  goal_orientation_tolerance: 0.05