scara_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  #goal_joint_tolerance: 0.0001
  #goal_position_tolerance: 0.0001
  #goal_orientation_tolerance: 0.001
sixaxis_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  #goal_joint_tolerance: 0.0001
  #goal_position_tolerance: 0.0001
  #goal_orientation_tolerance: 0.001
pillar_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  #goal_joint_tolerance: 0.0001
  #goal_position_tolerance: 0.0001
  #goal_orientation_tolerance: 0.001