scara_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - sj1
    - sj2
    - sj3
    - sEE
  gains:
    sj1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sj2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sj3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sEE:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
sixaxis_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - saj1
    - saj2
    - saj3
    - saj4
    - saj5
    - saj6
  gains:
    saj1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    saj2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    saj3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    saj4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    saj5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    saj6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
pillar_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - pj1
    - pj2
    - pj3
    - pj4
  gains:
    pj1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pj2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pj3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pj4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1