controller_list:
  - name: scara_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - sj1
      - sj2
      - sj3
      - sEE
  - name: sixaxis_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - saj1
      - saj2
      - saj3
      - saj4
      - saj5
      - saj6
  - name: pillar_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - pj1
      - pj2
      - pj3
      - pj4