controller_list:
  - name: sixaxis_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - saj1
      - saj2
      - saj3
      - saj4
      - saj5
      - saj6
      - saEE1
      - saEE2
  - name: scara_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - sj1
      - sj2
      - sj3
      - sjEE