controller_list:
  - name: fake_scara_controller
    type: $(arg fake_execution_type)
    joints:
      - arm1
      - arm2
      - arm3
      - arm4
      - Saugnapf
initial:  # Define initial robot poses per group
  - group: scara
    pose: pHome_scara