controller_list:
  - name: fake_scara_planninggroup_controller
    type: $(arg fake_execution_type)
    joints:
      - j1
      - j2
      - j3
      - j4
initial:  # Define initial robot poses per group
  - group: scara_planninggroup
    pose: home_pose