scara_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm1
    - arm2
    - arm3
    - arm4
    - Saugnapf
  gains:
    arm1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Saugnapf:
      p: 100
      d: 1
      i: 1
      i_clamp: 1