sixaxis_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_1
    - arm_2
    - arm_3
    - arm_4
    - arm_5
    - arm_6
    - Zange1
    - Zang2
  gains:
    arm_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Zange1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Zang2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1