controller_list:
  - name: sixaxis_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_1
      - arm_2
      - arm_3
      - arm_4
      - arm_5
      - arm_6
      - Zange1
      - Zang2